### ISSUE TITLE
Remove names

### ISSUE THREAD

**Issue by MustKnowInfo** [akshaywildfire/wethepeopleofindia.net#1]
Hey Akshay.

Thank you for creating such this website. Can you please remove all the names from the doctors/lawyer list since they (especially females) are getting harassed over phone calls?

Also, I;m running a similar website https://caa-nrc-protest.netlify.com/ but it's mostly focused on helping protesters in trouble by centralising information about how they can seek help.

Can you drop a link to the https://caa-nrc-protest.netlify.com/ somewhere in your website so that  people visiting your website can know of it too

**Comment by akshaywildfire** [comment]
Thank you for your feedback. Removing the names right away. Can you please email me a phone number on which I can call you. Send it to stopnrc@protonmail.com.
